# Site settings
title: Welcome
header-img: img/home-bg.jpg
email: james.risberg@gmail.com
description: "The personal site of James Risberg!"
baseurl: ""
url: "http://www.jamesrisberg.xyz"
twitter_username: JimmyRis
github_username:  jamesrisberg
facebook_username:  jamesrisberg

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
